name: 📈 Publish History Plot
on:
  schedule:
    - cron: "0 0 1 * *"
  push:
      branches:
        - main
jobs:
  post-plot-history:
    runs-on: ubuntu-latest

    steps:
      - name: 📀 Checks Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 🐍 Setup Python
        uses: actions/setup-python@v3.1.2
        
      - name: 🔠 Add all locale support
        run: |
            apt-get update
            apt-get install -y locales-all
            locale-gen pt_PT.UTF-8
            locale-gen pt_PT
            update-locale
            export LC_ALL=C

      - name: 📦 Install project requirements
        run: pip install -r requirements.txt

      - name: 📈 Post history plot
        env:
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        run: python post_plot_history.py
