name: ⛽️ Update Gas Prices from DRETT
on:
  schedule:
    - cron: "0 */6 * * *"
    - cron: "*/30 * * * 5,6,0,1"
  push:
    branches:
      - main
permissions: write-all
jobs:
  build:
    runs-on: harry-self-hosted-runner
    steps:
      - name: Checks out the repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Python
        uses: actions/setup-python@v4
      - name: Install dependencies
        run: apt-get install -y python3 python3-pip
      - name: Install project requirements
        run: pip3 install -r requirements.txt
      - name: Export data to file, add history and publish on Twitter
        env:
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        run: ping -c 5 joram.madeira.gov.pt
      - name: Commit gas information with history
        run: |
          git config --global user.name 'Dntfreitas'
          git config --global user.email 'dntfreitas123@gmail.com'
          git add gas_info.json
          git add history/gas_info_history.csv
          git add history/gas_info_history.json
          git diff-index --quiet HEAD || git commit -m "Update gas information"
          git push
